---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: silverwhite-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      #- https://copr.fedorainfracloud.org/coprs/lilay/topgrade/repo/fedora-%OS_VERSION%/lilay-topgrade-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/ilyaz/LACT/repo/fedora-%OS_VERSION%/ilyaz-LACT-fedora-%OS_VERSION%.repo
      #- https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-%OS_VERSION%/ublue-os-staging-fedora-%OS_VERSION%.repo
   
    install:
      #- distrobox
      #- fastfetch
      - langpacks-core-fr
      - langpacks-fr
      #- steam-devices
      #- topgrade
      - lact-libadwaita
      #- gnome-software
      
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      #- firefox
      #- firefox-langpacks
      - ibus-hangul
      - ibus-libpinyin
      - ibus-anthy
      - ibus-anthy-python
      - ibus-m17n
      - gnome-tour
      - yelp
      - solaar
      - input-leap
      - simple-scan
      - gnome-classic-session
      - gnome-shell-extension-apps-menu
      - gnome-shell-extension-launch-new-instance
      - gnome-shell-extension-places-menu
      - gnome-shell-extension-window-list
      - gnome-shell-extension-background-logo
      - gnome-shell-extension-blur-my-shell
      - gnome-shell-extension-logomenu
      - gnome-shell-extension-search-light
      - gnome-shell-extension-user-theme
      - gnome-shell-extension-tailscale
      - input-remapper
      #- google-noto-sans-balinese-fonts
      #- google-noto-sans-cjk-fonts
      #- google-noto-sans-javanese-fonts
      #- google-noto-sans-sundanese-fonts
      #- nvtop
      #- htop
      #- fedora-logos
      #- ublue-os-udev-rules #remove when main is updated.
      
  #- type: default-flatpaks
  #  notify: true # Send notification after install/uninstall is finished (true/false)
  #  system:
  #    # If no repo information is specified, Flathub will be used by default
  #    install:
  #    remove:
  #  user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
