---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: silverwhite-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/ilyaz/LACT/repo/fedora-%OS_VERSION%/ilyaz-LACT-fedora-%OS_VERSION%.repo
      
    install:
      - langpacks-core-fr
      - langpacks-fr
      - lact-libadwaita
     
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - ibus-hangul
      - ibus-libpinyin
      - ibus-anthy
      - ibus-anthy-python
      - ibus-m17n
      - gnome-tour
      - yelp
      - solaar
      - input-leap
      - simple-scan
      - gnome-classic-session
      - gnome-shell-extension-apps-menu
      - gnome-shell-extension-logo-menu
      - gnome-shell-extension-launch-new-instance
      - gnome-shell-extension-places-menu
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-dash-to-dock
      - gnome-shell-extension-caffeine
      - gnome-shell-extension-window-list
      - gnome-shell-extension-blur-my-shell
      - gnome-shell-extension-search-light
      - gnome-shell-extension-user-theme
      - gnome-shell-theme-yaru
      - yaru-sound-theme
      - yaru-icon-theme
      - yaru-gtksourceview-theme
      - yaru-gtk4-theme
      - yaru-gtk3-theme
      - yaru-gtk2-theme
      - yaru-theme
      - gnome-shell-extension-tailscale-gnome-qs
      - input-remapper
      - google-noto-fonts-all
      - default-fonts-cjk-serif
      - default-fonts-core-serif
      - default-fonts-as
      - default-fonts-te
      - default-fonts-dv
      - default-fonts-th
      - default-fonts-or
      - default-fonts-si
      - default-fonts-ta
      - default-fonts-sat
      - default-fonts-cjk-mono
      - default-fonts-mni
      - default-fonts-core-math
      - default-fonts-lo
      - default-fonts-km
      - default-fonts-kn
      - default-fonts-yi
      - default-fonts-pa
      - default-fonts-gu
      - default-fonts-ka
      - default-fonts-am
      - default-fonts-mr
      - default-fonts-chr
      - default-fonts-iu
      - default-fonts-bn
      - default-fonts-mai
      - default-fonts-hy
      - default-fonts-ar
      - default-fonts-he
      - default-fonts-zu
      - default-fonts-ast
      - default-fonts-hi
      - default-fonts-other-serif
      - default-fonts-other-sans
      - default-fonts-core-emoji
      - google-noto-sans-balinese-fonts
      - google-noto-sans-cjk-fonts
      - google-noto-sans-javanese-fonts
      - google-noto-sans-sundanese-fonts
      #- google-noto-fonts-common
      #- google-noto-sans-vf-fonts
      - google-noto-sans-devanagari-vf-fonts
      #- google-noto-sans-mono-vf-fonts
      #- google-noto-serif-vf-fonts
      - google-noto-sans-hebrew-vf-fonts
      - google-noto-naskh-arabic-vf-fonts
      - google-noto-sans-arabic-vf-fonts
      - google-noto-sans-armenian-vf-fonts
      - google-noto-sans-bengali-vf-fonts
      - google-noto-sans-canadian-aboriginal-vf-fonts
      - google-noto-sans-cherokee-vf-fonts
      - google-noto-sans-ethiopic-vf-fonts
      - google-noto-sans-georgian-vf-fonts
      - google-noto-sans-gujarati-vf-fonts
      - google-noto-sans-gurmukhi-vf-fonts
      - google-noto-sans-kannada-vf-fonts
      - google-noto-sans-khmer-vf-fonts
      - google-noto-sans-lao-vf-fonts
      - google-noto-sans-math-fonts
      - google-noto-sans-meetei-mayek-vf-fonts
      - google-noto-sans-ol-chiki-vf-fonts
      - google-noto-sans-oriya-vf-fonts
      - google-noto-sans-sinhala-vf-fonts
      - google-noto-sans-symbols-2-fonts
      - google-noto-sans-symbols-vf-fonts
      - google-noto-sans-tamil-vf-fonts
      - google-noto-sans-telugu-vf-fonts
      - google-noto-sans-thaana-vf-fonts
      - google-noto-sans-thai-vf-fonts
      - google-noto-serif-armenian-vf-fonts
      - google-noto-serif-bengali-vf-fonts
      - google-noto-serif-devanagari-vf-fonts
      - google-noto-serif-ethiopic-vf-fonts
      - google-noto-serif-georgian-vf-fonts
      - google-noto-serif-gujarati-vf-fonts
      - google-noto-serif-gurmukhi-vf-fonts
      - google-noto-serif-hebrew-vf-fonts
      - google-noto-serif-kannada-vf-fonts
      - google-noto-serif-khmer-vf-fonts
      - google-noto-serif-lao-vf-fonts
      - google-noto-serif-oriya-vf-fonts
      - google-noto-serif-sinhala-vf-fonts
      - google-noto-serif-tamil-vf-fonts
      - google-noto-serif-telugu-vf-fonts
      - google-noto-serif-thai-vf-fonts
      - google-noto-color-emoji-fonts
      - google-noto-sans-mono-cjk-vf-fonts
      - google-noto-serif-cjk-vf-fonts
      - google-noto-znamenny-musical-notation-fonts
      - google-noto-traditional-nushu-vf-fonts
      - google-noto-traditional-nushu-fonts
      - google-noto-serif-yezidi-vf-fonts
      - google-noto-serif-yezidi-fonts
      - google-noto-serif-vithkuqi-vf-fonts
      - google-noto-serif-vithkuqi-fonts
      - google-noto-serif-toto-vf-fonts
      - google-noto-serif-toto-fonts
      - google-noto-serif-tibetan-vf-fonts
      - google-noto-serif-tibetan-fonts
      - google-noto-serif-thai-fonts
      - google-noto-serif-telugu-fonts
      - google-noto-serif-tangut-fonts
      - google-noto-serif-tamil-fonts
      - google-noto-serif-sinhala-fonts
      - google-noto-serif-ottoman-siyaq-fonts
      - google-noto-serif-oriya-fonts
      - google-noto-serif-old-uyghur-fonts
      - google-noto-serif-np-hmong-vf-fonts
      - google-noto-serif-np-hmong-fonts
      - google-noto-serif-myanmar-fonts
      - google-noto-serif-malayalam-vf-fonts
      - google-noto-serif-malayalam-fonts
      - google-noto-serif-makasar-fonts
      - google-noto-serif-lao-fonts
      - google-noto-serif-khojki-vf-fonts
      - google-noto-serif-khojki-fonts
      - google-noto-serif-khmer-fonts
      - google-noto-serif-khitan-small-script-fonts
      - google-noto-serif-kannada-fonts
      - google-noto-serif-hebrew-fonts
      - google-noto-serif-gurmukhi-fonts
      - google-noto-serif-gujarati-fonts
      - google-noto-serif-grantha-fonts
      - google-noto-serif-georgian-fonts
      - google-noto-serif-fonts
      - google-noto-serif-ethiopic-fonts
      - google-noto-serif-dogra-fonts
      - google-noto-serif-dives-akuru-fonts
      - google-noto-serif-devanagari-fonts
      - google-noto-serif-bengali-fonts
      - google-noto-serif-balinese-fonts
      - google-noto-serif-armenian-fonts
      - google-noto-serif-ahom-fonts
      - google-noto-sans-zanabazar-square-fonts
      - google-noto-sans-yi-fonts
      - google-noto-sans-warang-citi-fonts
      - google-noto-sans-wancho-fonts
      - google-noto-sans-vithkuqi-vf-fonts
      - google-noto-sans-vithkuqi-fonts
      - google-noto-sans-vai-fonts
      - google-noto-sans-ugaritic-fonts
      - google-noto-sans-tirhuta-fonts
      - google-noto-sans-tifinagh-tawellemmet-fonts
      - google-noto-sans-tifinagh-sil-fonts
      - google-noto-sans-tifinagh-rhissa-ixa-fonts
      - google-noto-sans-tifinagh-hawad-fonts
      - google-noto-sans-tifinagh-ghat-fonts
      - google-noto-sans-tifinagh-fonts
      - google-noto-sans-tifinagh-azawagh-fonts
      - google-noto-sans-tifinagh-apt-fonts
      - google-noto-sans-tifinagh-air-fonts
      - google-noto-sans-tifinagh-ahaggar-fonts
      - google-noto-sans-tifinagh-agraw-imazighen-fonts
      - google-noto-sans-tifinagh-adrar-fonts
      - google-noto-sans-thai-looped-fonts
      - google-noto-sans-thai-fonts
      - google-noto-sans-thaana-fonts
      - google-noto-sans-telugu-ui-vf-fonts
      - google-noto-sans-telugu-ui-fonts
      - google-noto-sans-telugu-fonts
      - google-noto-sans-tangsa-vf-fonts
      - google-noto-sans-tangsa-fonts
      - google-noto-sans-tamil-ui-vf-fonts
      - google-noto-sans-tamil-ui-fonts
      - google-noto-sans-tamil-supplement-fonts
      - google-noto-sans-tamil-fonts
      - google-noto-sans-takri-fonts
      - google-noto-sans-tai-viet-fonts
      - google-noto-sans-tai-tham-vf-fonts
      - google-noto-sans-tai-tham-fonts
      - google-noto-sans-tai-le-fonts
      - google-noto-sans-tagbanwa-fonts
      - google-noto-sans-tagalog-fonts
      - google-noto-sans-syriac-western-vf-fonts
      - google-noto-sans-syriac-western-fonts
      - google-noto-sans-syriac-vf-fonts
      - google-noto-sans-syriac-fonts
      - google-noto-sans-syriac-eastern-vf-fonts
      - google-noto-sans-syriac-eastern-fonts
      - google-noto-sans-symbols-fonts
      - google-noto-sans-syloti-nagri-fonts
      - google-noto-sans-sundanese-vf-fonts
      - google-noto-sans-soyombo-fonts
      - google-noto-sans-sora-sompeng-vf-fonts
      - google-noto-sans-sora-sompeng-fonts
      - google-noto-sans-sogdian-fonts
      - google-noto-sans-sinhala-ui-fonts
      - google-noto-sans-sinhala-fonts
      - google-noto-sans-signwriting-fonts
      - google-noto-sans-siddham-fonts
      - google-noto-sans-shavian-fonts
      - google-noto-sans-sharada-fonts
      - google-noto-sans-saurashtra-fonts
      - google-noto-sans-samaritan-fonts
      - google-noto-sans-runic-fonts
      - google-noto-sans-rejang-fonts
      - google-noto-sans-psalter-pahlavi-fonts
      - google-noto-sans-phoenician-fonts
      - google-noto-sans-phagspa-fonts
      - google-noto-sans-pau-cin-hau-fonts
      - google-noto-sans-palmyrene-fonts
      - google-noto-sans-pahawh-hmong-fonts
      - google-noto-sans-osmanya-fonts
      - google-noto-sans-osage-fonts
      - google-noto-sans-oriya-fonts
      - google-noto-sans-old-turkic-fonts
      - google-noto-sans-old-south-arabian-fonts
      - google-noto-sans-old-sogdian-fonts
      - google-noto-sans-old-persian-fonts
      - google-noto-sans-old-permic-fonts
      - google-noto-sans-old-north-arabian-fonts
      - google-noto-sans-old-italic-fonts
      - google-noto-sans-old-hungarian-fonts
      - google-noto-sans-ol-chiki-fonts
      - google-noto-sans-ogham-fonts
      - google-noto-sans-nushu-fonts
      - google-noto-sans-nko-unjoined-vf-fonts
      - google-noto-sans-nko-unjoined-fonts
      - google-noto-sans-nko-fonts
      - google-noto-sans-newa-fonts
      - google-noto-sans-new-tai-lue-vf-fonts
      - google-noto-sans-new-tai-lue-fonts
      - google-noto-sans-nandinagari-fonts
      - google-noto-sans-nag-mundari-vf-fonts
      - google-noto-sans-nag-mundari-fonts
      - google-noto-sans-nabataean-fonts
      - google-noto-sans-myanmar-vf-fonts
      - google-noto-sans-myanmar-fonts
      - google-noto-sans-multani-fonts
      - google-noto-sans-mro-fonts
      - google-noto-sans-mono-fonts
      - google-noto-sans-mongolian-fonts
      - google-noto-sans-modi-fonts
      - google-noto-sans-miao-fonts
      - google-noto-sans-meroitic-fonts
      - google-noto-sans-mende-kikakui-fonts
      - google-noto-sans-meetei-mayek-fonts
      - google-noto-sans-medefaidrin-vf-fonts
      - google-noto-sans-medefaidrin-fonts
      - google-noto-sans-mayan-numerals-fonts
      - google-noto-sans-masaram-gondi-fonts
      - google-noto-sans-marchen-fonts
      - google-noto-sans-manichaean-fonts
      - google-noto-sans-mandaic-fonts
      - google-noto-sans-malayalam-vf-fonts
      - google-noto-sans-malayalam-ui-vf-fonts
      - google-noto-sans-malayalam-ui-fonts
      - google-noto-sans-malayalam-fonts
      - google-noto-sans-mahajani-fonts
      - google-noto-sans-lydian-fonts
      - google-noto-sans-lycian-fonts
      - google-noto-sans-lisu-vf-fonts
      - google-noto-sans-lisu-fonts
      - google-noto-sans-linear-b-fonts
      - google-noto-sans-linear-a-fonts
      - google-noto-sans-limbu-fonts
      - google-noto-sans-lepcha-fonts
      - google-noto-sans-lao-looped-vf-fonts
      - google-noto-sans-lao-looped-fonts
      - google-noto-sans-lao-fonts
      - google-noto-sans-khudawadi-fonts
      - google-noto-sans-khojki-fonts
      - google-noto-sans-khmer-fonts
      - google-noto-sans-kharoshthi-fonts
      - google-noto-sans-kayah-li-vf-fonts
      - google-noto-sans-kayah-li-fonts
      - google-noto-sans-kawi-vf-fonts
      - google-noto-sans-kawi-fonts
      - google-noto-sans-kannada-ui-vf-fonts
      - google-noto-sans-kannada-ui-fonts
      - google-noto-sans-kannada-fonts
      - google-noto-sans-kaithi-fonts
      - google-noto-sans-javanese-vf-fonts
      - google-noto-sans-inscriptional-parthian-fonts
      - google-noto-sans-inscriptional-pahlavi-fonts
      - google-noto-sans-indic-siyaq-numbers-fonts
      - google-noto-sans-imperial-aramaic-fonts
      - google-noto-sans-hebrew-fonts
      - google-noto-sans-hatran-fonts
      - google-noto-sans-hanunoo-fonts
      - google-noto-sans-hanifi-rohingya-vf-fonts
      - google-noto-sans-hanifi-rohingya-fonts
      - google-noto-sans-gurmukhi-ui-fonts
      - google-noto-sans-gurmukhi-fonts
      - google-noto-sans-gunjala-gondi-vf-fonts
      - google-noto-sans-gunjala-gondi-fonts
      - google-noto-sans-gujarati-ui-fonts
      - google-noto-sans-gujarati-fonts
      - google-noto-sans-grantha-fonts
      - google-noto-sans-gothic-fonts
      - google-noto-sans-glagolitic-fonts
      - google-noto-sans-georgian-fonts
      - google-noto-sans-fonts
      - google-noto-sans-ethiopic-fonts
      - google-noto-sans-elymaic-fonts
      - google-noto-sans-elbasan-fonts
      - google-noto-sans-egyptian-hieroglyphs-fonts
      - google-noto-sans-duployan-fonts
      - google-noto-sans-devanagari-ui-fonts
      - google-noto-sans-devanagari-fonts
      - google-noto-sans-deseret-fonts
      - google-noto-sans-cypro-minoan-fonts
      - google-noto-sans-cypriot-fonts
      - google-noto-sans-cuneiform-fonts
      - google-noto-sans-coptic-fonts
      - google-noto-sans-chorasmian-fonts
      - google-noto-sans-cherokee-fonts
      - google-noto-sans-cham-vf-fonts
      - google-noto-sans-cham-fonts
      - google-noto-sans-chakma-fonts
      - google-noto-sans-caucasian-albanian-fonts
      - google-noto-sans-carian-fonts
      - google-noto-sans-canadian-aboriginal-fonts
      - google-noto-sans-buhid-fonts
      - google-noto-sans-buginese-fonts
      - google-noto-sans-brahmi-fonts
      - google-noto-sans-bhaiksuki-fonts
      - google-noto-sans-bengali-ui-fonts
      - google-noto-sans-bengali-fonts
      - google-noto-sans-batak-fonts
      - google-noto-sans-bassa-vah-vf-fonts
      - google-noto-sans-bassa-vah-fonts
      - google-noto-sans-bamum-vf-fonts
      - google-noto-sans-bamum-fonts
      - google-noto-sans-balinese-vf-fonts
      - google-noto-sans-avestan-fonts
      - google-noto-sans-armenian-fonts
      - google-noto-sans-arabic-ui-vf-fonts
      - google-noto-sans-arabic-ui-fonts
      - google-noto-sans-arabic-fonts
      - google-noto-sans-anatolian-hieroglyphs-fonts
      - google-noto-sans-adlam-vf-fonts
      - google-noto-sans-adlam-unjoined-vf-fonts
      - google-noto-sans-adlam-unjoined-fonts
      - google-noto-sans-adlam-fonts
      - google-noto-rashi-hebrew-vf-fonts
      - google-noto-rashi-hebrew-fonts
      - google-noto-nastaliq-urdu-vf-fonts
      - google-noto-nastaliq-urdu-fonts
      - google-noto-naskh-arabic-ui-vf-fonts
      - google-noto-naskh-arabic-ui-fonts
      - google-noto-naskh-arabic-fonts
      - google-noto-music-fonts
      - google-noto-kufi-arabic-vf-fonts
      - google-noto-kufi-arabic-fonts
      - google-noto-fangsong-kss-vertical-fonts
      - google-noto-fangsong-kss-rotated-fonts
      
  #- type: default-flatpaks
  #  notify: true # Send notification after install/uninstall is finished (true/false)
  #  system:
  #    # If no repo information is specified, Flathub will be used by default
  #    install:
  #    remove:
  #  user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
